# exceptions.py
class NoteNotFoundException(Exception):
    pass